# Deploy to Cloud Run Composite Action
#
# Push to Artifact Registry and deploy to Cloud Run.

name: 'Deploy to Cloud Run'
description: 'Push image to Artifact Registry and deploy to Cloud Run'

inputs:
  service-dir:
    description: 'Service directory name'
    required: true
  gcp-project-id:
    description: 'GCP project ID'
    required: true
  gcp-region:
    description: 'GCP region'
    required: true
  workload-identity-provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service-account:
    description: 'GCP Service Account'
    required: true
  discord-public-key:
    description: 'Discord public key for signature validation'
    required: false
    default: '398803f0f03317b6dc57069dbe7820e5f6cf7d5ff43ad6219710b19b0b49c159'

runs:
  using: 'composite'
  steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: |
        gcloud auth configure-docker ${{ inputs.gcp-region }}-docker.pkg.dev --quiet

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Build and push image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      env:
        AR_REPO: ${{ inputs.gcp-region }}-docker.pkg.dev/${{ inputs.gcp-project-id }}/discord-services
      with:
        context: ./services/${{ inputs.service-dir }}
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.AR_REPO }}/${{ inputs.service-dir }}:${{ github.sha }}
          ${{ env.AR_REPO }}/${{ inputs.service-dir }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Cloud Run
      shell: bash
      run: |
        gcloud run deploy discord-${{ inputs.service-dir }} \
          --image ${{ inputs.gcp-region }}-docker.pkg.dev/${{ inputs.gcp-project-id }}/discord-services/${{ inputs.service-dir }}:${{ github.sha }} \
          --region ${{ inputs.gcp-region }} \
          --service-account cloudrun-runtime@${{ inputs.gcp-project-id }}.iam.gserviceaccount.com \
          --cpu 1 \
          --memory 512Mi \
          --max-instances 1 \
          --concurrency 80 \
          --cpu-boost \
          --set-env-vars "DISCORD_PUBLIC_KEY=${{ inputs.discord-public-key }},GOOGLE_CLOUD_PROJECT=${{ inputs.gcp-project-id }}" \
          --no-allow-unauthenticated
