# golangci-lint configuration for Go/Gin service
version: '2'

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment # Optimization, not a correctness issue
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/pmgledhill102/discord-bot-test-suite
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # Unhandled errors (we handle these explicitly where needed)
  staticcheck:
    checks:
      - all
      - '-SA1019' # Ignore deprecation warnings (pubsub v1 → v2 migration pending)

issues:
  exclude-rules:
    # Allow log.Fatal in main
    - path: main\.go
      linters:
        - gocritic
      text: 'exitAfterDefer'
